# fly.toml app configuration file generated for a123213-1726633141-server on 2024-09-18T04:19:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'a123213-1726633141-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
